name: mirrordiffusion
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - pytorch-cuda=11.6
  - torchvision
  - pytorch==1.13.1
  - pip:
    - accelerate==0.26.1
    - gradio
    - numpy==1.24.4
    - #opencv-python-headless
    - psutil
    - tqdm==4.66.1
    - salesforce-lavis
